


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import './globals.css'

import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

import Main from '../components/Main/main';

//import Time from '../components/date_clock/time';
import Head from 'next/head';
import Sides from '../components/Sides/sides';


export default function RootLayout({children}) {
  return (

    <html lang="en">
      <Head>
         <link rel="preconnect" href="https://cdn.fonts.net"/>
         <link href="https://cdn.fonts.net/kit/7412bbc1-99ea-4a5a-b049-289000102a23/7412bbc1-99ea-4a5a-b049-289000102a23.css" rel="stylesheet" />

         <link rel="stylesheet" href="https://use.typekit.net/gjy6qgm.css"></link>
         <script src="https://kit.fontawesome.com/52d3a0a7c6.js" crossorigin="anonymous"></script> 
         <title>bimcopilot.com</title>      
      </Head>

      <body >
        <Sides/>                   
        {children}
      </body>
    </html>   
  )
}